############## All Tools Variables ################
CXXSRC_FILES_SUFFIXES     := cxx cc C cpp
CSRC_FILES_SUFFIXES       := c
FORTRANSRC_FILES_SUFFIXES := F f77 f F77
SRC_FILES_SUFFIXES        := $(CXXSRC_FILES_SUFFIXES) $(CSRC_FILES_SUFFIXES) $(FORTRANSRC_FILES_SUFFIXES)
SCRAM_ADMIN_DIR           := .SCRAM/$(SCRAM_ARCH)
SCRAM_TOOLS_DIR           := $(SCRAM_ADMIN_DIR)/timestamps
CFLAGS:=
BIN_CFLAGS:=
TEST_CFLAGS:=
EDM_CFLAGS:=
CAPABILITIES_CFLAGS:=
LCGDICT_CFLAGS:=
ROOTDICT_CFLAGS:=
DEV_CFLAGS:=
RELEASE_CFLAGS:=
REM_CFLAGS:=
REM_BIN_CFLAGS:=
REM_TEST_CFLAGS:=
REM_EDM_CFLAGS:=
REM_CAPABILITIES_CFLAGS:=
REM_LCGDICT_CFLAGS:=
REM_ROOTDICT_CFLAGS:=
REM_DEV_CFLAGS:=
REM_RELEASE_CFLAGS:=
CPPDEFINES:=
BIN_CPPDEFINES:=
TEST_CPPDEFINES:=
EDM_CPPDEFINES:=
CAPABILITIES_CPPDEFINES:=
LCGDICT_CPPDEFINES:=
ROOTDICT_CPPDEFINES:=
DEV_CPPDEFINES:=
RELEASE_CPPDEFINES:=
REM_CPPDEFINES:=
REM_BIN_CPPDEFINES:=
REM_TEST_CPPDEFINES:=
REM_EDM_CPPDEFINES:=
REM_CAPABILITIES_CPPDEFINES:=
REM_LCGDICT_CPPDEFINES:=
REM_ROOTDICT_CPPDEFINES:=
REM_DEV_CPPDEFINES:=
REM_RELEASE_CPPDEFINES:=
CPPFLAGS:=
BIN_CPPFLAGS:=
TEST_CPPFLAGS:=
EDM_CPPFLAGS:=
CAPABILITIES_CPPFLAGS:=
LCGDICT_CPPFLAGS:=
ROOTDICT_CPPFLAGS:=
DEV_CPPFLAGS:=
RELEASE_CPPFLAGS:=
REM_CPPFLAGS:=
REM_BIN_CPPFLAGS:=
REM_TEST_CPPFLAGS:=
REM_EDM_CPPFLAGS:=
REM_CAPABILITIES_CPPFLAGS:=
REM_LCGDICT_CPPFLAGS:=
REM_ROOTDICT_CPPFLAGS:=
REM_DEV_CPPFLAGS:=
REM_RELEASE_CPPFLAGS:=
CSHAREDOBJECTFLAGS:=
BIN_CSHAREDOBJECTFLAGS:=
TEST_CSHAREDOBJECTFLAGS:=
EDM_CSHAREDOBJECTFLAGS:=
CAPABILITIES_CSHAREDOBJECTFLAGS:=
LCGDICT_CSHAREDOBJECTFLAGS:=
ROOTDICT_CSHAREDOBJECTFLAGS:=
DEV_CSHAREDOBJECTFLAGS:=
RELEASE_CSHAREDOBJECTFLAGS:=
REM_CSHAREDOBJECTFLAGS:=
REM_BIN_CSHAREDOBJECTFLAGS:=
REM_TEST_CSHAREDOBJECTFLAGS:=
REM_EDM_CSHAREDOBJECTFLAGS:=
REM_CAPABILITIES_CSHAREDOBJECTFLAGS:=
REM_LCGDICT_CSHAREDOBJECTFLAGS:=
REM_ROOTDICT_CSHAREDOBJECTFLAGS:=
REM_DEV_CSHAREDOBJECTFLAGS:=
REM_RELEASE_CSHAREDOBJECTFLAGS:=
CXXFLAGS:=
BIN_CXXFLAGS:=
TEST_CXXFLAGS:=
EDM_CXXFLAGS:=
CAPABILITIES_CXXFLAGS:=
LCGDICT_CXXFLAGS:=
ROOTDICT_CXXFLAGS:=
DEV_CXXFLAGS:=
RELEASE_CXXFLAGS:=
REM_CXXFLAGS:=
REM_BIN_CXXFLAGS:=
REM_TEST_CXXFLAGS:=
REM_EDM_CXXFLAGS:=
REM_CAPABILITIES_CXXFLAGS:=
REM_LCGDICT_CXXFLAGS:=
REM_ROOTDICT_CXXFLAGS:=
REM_DEV_CXXFLAGS:=
REM_RELEASE_CXXFLAGS:=
CXXSHAREDFLAGS:=
BIN_CXXSHAREDFLAGS:=
TEST_CXXSHAREDFLAGS:=
EDM_CXXSHAREDFLAGS:=
CAPABILITIES_CXXSHAREDFLAGS:=
LCGDICT_CXXSHAREDFLAGS:=
ROOTDICT_CXXSHAREDFLAGS:=
DEV_CXXSHAREDFLAGS:=
RELEASE_CXXSHAREDFLAGS:=
REM_CXXSHAREDFLAGS:=
REM_BIN_CXXSHAREDFLAGS:=
REM_TEST_CXXSHAREDFLAGS:=
REM_EDM_CXXSHAREDFLAGS:=
REM_CAPABILITIES_CXXSHAREDFLAGS:=
REM_LCGDICT_CXXSHAREDFLAGS:=
REM_ROOTDICT_CXXSHAREDFLAGS:=
REM_DEV_CXXSHAREDFLAGS:=
REM_RELEASE_CXXSHAREDFLAGS:=
CXXSHAREDOBJECTFLAGS:=
BIN_CXXSHAREDOBJECTFLAGS:=
TEST_CXXSHAREDOBJECTFLAGS:=
EDM_CXXSHAREDOBJECTFLAGS:=
CAPABILITIES_CXXSHAREDOBJECTFLAGS:=
LCGDICT_CXXSHAREDOBJECTFLAGS:=
ROOTDICT_CXXSHAREDOBJECTFLAGS:=
DEV_CXXSHAREDOBJECTFLAGS:=
RELEASE_CXXSHAREDOBJECTFLAGS:=
REM_CXXSHAREDOBJECTFLAGS:=
REM_BIN_CXXSHAREDOBJECTFLAGS:=
REM_TEST_CXXSHAREDOBJECTFLAGS:=
REM_EDM_CXXSHAREDOBJECTFLAGS:=
REM_CAPABILITIES_CXXSHAREDOBJECTFLAGS:=
REM_LCGDICT_CXXSHAREDOBJECTFLAGS:=
REM_ROOTDICT_CXXSHAREDOBJECTFLAGS:=
REM_DEV_CXXSHAREDOBJECTFLAGS:=
REM_RELEASE_CXXSHAREDOBJECTFLAGS:=
FFLAGS:=
BIN_FFLAGS:=
TEST_FFLAGS:=
EDM_FFLAGS:=
CAPABILITIES_FFLAGS:=
LCGDICT_FFLAGS:=
ROOTDICT_FFLAGS:=
DEV_FFLAGS:=
RELEASE_FFLAGS:=
REM_FFLAGS:=
REM_BIN_FFLAGS:=
REM_TEST_FFLAGS:=
REM_EDM_FFLAGS:=
REM_CAPABILITIES_FFLAGS:=
REM_LCGDICT_FFLAGS:=
REM_ROOTDICT_FFLAGS:=
REM_DEV_FFLAGS:=
REM_RELEASE_FFLAGS:=
FOPTIMISEDFLAGS:=
BIN_FOPTIMISEDFLAGS:=
TEST_FOPTIMISEDFLAGS:=
EDM_FOPTIMISEDFLAGS:=
CAPABILITIES_FOPTIMISEDFLAGS:=
LCGDICT_FOPTIMISEDFLAGS:=
ROOTDICT_FOPTIMISEDFLAGS:=
DEV_FOPTIMISEDFLAGS:=
RELEASE_FOPTIMISEDFLAGS:=
REM_FOPTIMISEDFLAGS:=
REM_BIN_FOPTIMISEDFLAGS:=
REM_TEST_FOPTIMISEDFLAGS:=
REM_EDM_FOPTIMISEDFLAGS:=
REM_CAPABILITIES_FOPTIMISEDFLAGS:=
REM_LCGDICT_FOPTIMISEDFLAGS:=
REM_ROOTDICT_FOPTIMISEDFLAGS:=
REM_DEV_FOPTIMISEDFLAGS:=
REM_RELEASE_FOPTIMISEDFLAGS:=
FSHAREDOBJECTFLAGS:=
BIN_FSHAREDOBJECTFLAGS:=
TEST_FSHAREDOBJECTFLAGS:=
EDM_FSHAREDOBJECTFLAGS:=
CAPABILITIES_FSHAREDOBJECTFLAGS:=
LCGDICT_FSHAREDOBJECTFLAGS:=
ROOTDICT_FSHAREDOBJECTFLAGS:=
DEV_FSHAREDOBJECTFLAGS:=
RELEASE_FSHAREDOBJECTFLAGS:=
REM_FSHAREDOBJECTFLAGS:=
REM_BIN_FSHAREDOBJECTFLAGS:=
REM_TEST_FSHAREDOBJECTFLAGS:=
REM_EDM_FSHAREDOBJECTFLAGS:=
REM_CAPABILITIES_FSHAREDOBJECTFLAGS:=
REM_LCGDICT_FSHAREDOBJECTFLAGS:=
REM_ROOTDICT_FSHAREDOBJECTFLAGS:=
REM_DEV_FSHAREDOBJECTFLAGS:=
REM_RELEASE_FSHAREDOBJECTFLAGS:=
LDFLAGS:=
BIN_LDFLAGS:=
TEST_LDFLAGS:=
EDM_LDFLAGS:=
CAPABILITIES_LDFLAGS:=
LCGDICT_LDFLAGS:=
ROOTDICT_LDFLAGS:=
DEV_LDFLAGS:=
RELEASE_LDFLAGS:=
REM_LDFLAGS:=
REM_BIN_LDFLAGS:=
REM_TEST_LDFLAGS:=
REM_EDM_LDFLAGS:=
REM_CAPABILITIES_LDFLAGS:=
REM_LCGDICT_LDFLAGS:=
REM_ROOTDICT_LDFLAGS:=
REM_DEV_LDFLAGS:=
REM_RELEASE_LDFLAGS:=
LD_UNIT:=
BIN_LD_UNIT:=
TEST_LD_UNIT:=
EDM_LD_UNIT:=
CAPABILITIES_LD_UNIT:=
LCGDICT_LD_UNIT:=
ROOTDICT_LD_UNIT:=
DEV_LD_UNIT:=
RELEASE_LD_UNIT:=
REM_LD_UNIT:=
REM_BIN_LD_UNIT:=
REM_TEST_LD_UNIT:=
REM_EDM_LD_UNIT:=
REM_CAPABILITIES_LD_UNIT:=
REM_LCGDICT_LD_UNIT:=
REM_ROOTDICT_LD_UNIT:=
REM_DEV_LD_UNIT:=
REM_RELEASE_LD_UNIT:=
REM_CXXFLAGS:=
BIN_REM_CXXFLAGS:=
TEST_REM_CXXFLAGS:=
EDM_REM_CXXFLAGS:=
CAPABILITIES_REM_CXXFLAGS:=
LCGDICT_REM_CXXFLAGS:=
ROOTDICT_REM_CXXFLAGS:=
DEV_REM_CXXFLAGS:=
RELEASE_REM_CXXFLAGS:=
REM_REM_CXXFLAGS:=
REM_BIN_REM_CXXFLAGS:=
REM_TEST_REM_CXXFLAGS:=
REM_EDM_REM_CXXFLAGS:=
REM_CAPABILITIES_REM_CXXFLAGS:=
REM_LCGDICT_REM_CXXFLAGS:=
REM_ROOTDICT_REM_CXXFLAGS:=
REM_DEV_REM_CXXFLAGS:=
REM_RELEASE_REM_CXXFLAGS:=
ALL_COMPILER_FLAGS := CFLAGS CPPDEFINES CPPFLAGS CSHAREDOBJECTFLAGS CXXFLAGS CXXSHAREDFLAGS CXXSHAREDOBJECTFLAGS FFLAGS FOPTIMISEDFLAGS FSHAREDOBJECTFLAGS LDFLAGS LD_UNIT REM_CXXFLAGS 
SCRAM_MULTIPLE_COMPILERS := yes
SCRAM_DEFAULT_COMPILER    := gcc
SCRAM_COMPILER            := $(SCRAM_DEFAULT_COMPILER)
ifdef COMPILER
SCRAM_COMPILER            := $(COMPILER)
endif
CXX_TYPE_COMPILER := cxxcompiler
C_TYPE_COMPILER := ccompiler
F77_TYPE_COMPILER := f77compiler
ifndef SCRAM_IGNORE_MISSING_COMPILERS
$(if $(wildcard $(SCRAM_TOOLS_DIR)/$(SCRAM_COMPILER)-$(CXX_TYPE_COMPILER)),,$(info ****WARNING: You have selected $(SCRAM_COMPILER) as compiler but there is no $(SCRAM_COMPILER)-$(CXX_TYPE_COMPILER) tool setup. Default compiler $(SCRAM_DEFAULT_COMPILER)-$(CXX_TYPE_COMPILER) will be used to comple CXX files))
$(if $(wildcard $(SCRAM_TOOLS_DIR)/$(SCRAM_COMPILER)-$(C_TYPE_COMPILER)),,$(info ****WARNING: You have selected $(SCRAM_COMPILER) as compiler but there is no $(SCRAM_COMPILER)-$(C_TYPE_COMPILER) tool setup. Default compiler $(SCRAM_DEFAULT_COMPILER)-$(C_TYPE_COMPILER) will be used to comple C files))
$(if $(wildcard $(SCRAM_TOOLS_DIR)/$(SCRAM_COMPILER)-$(F77_TYPE_COMPILER)),,$(info ****WARNING: You have selected $(SCRAM_COMPILER) as compiler but there is no $(SCRAM_COMPILER)-$(F77_TYPE_COMPILER) tool setup. Default compiler $(SCRAM_DEFAULT_COMPILER)-$(F77_TYPE_COMPILER) will be used to comple F77 files))
endif
GCC_CXXCOMPILER_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/gcc/4.7.2
CXX:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/gcc/4.7.2/bin/c++
GCC_CCOMPILER_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/gcc/4.7.2
CC:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/gcc/4.7.2/bin/gcc
GCC_F77COMPILER_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/gcc/4.7.2
FC:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/gcc/4.7.2/bin/gfortran

cxxcompiler := cxxcompiler
ALL_TOOLS  += cxxcompiler
cxxcompiler_LOC_USE   := $(if $(strip $(wildcard $(LOCALTOP)/$(SCRAM_TOOLS_DIR)/$(SCRAM_COMPILER)-cxxcompiler)),$(SCRAM_COMPILER)-cxxcompiler,$(SCRAM_DEFAULT_COMPILER)-cxxcompiler)
cxxcompiler_EX_USE    := $(cxxcompiler_LOC_USE)
cxxcompiler_INIT_FUNC := $$(eval $$(call ProductCommonVars,cxxcompiler,,,cxxcompiler))


ccompiler := ccompiler
ALL_TOOLS  += ccompiler
ccompiler_LOC_USE   := $(if $(strip $(wildcard $(LOCALTOP)/$(SCRAM_TOOLS_DIR)/$(SCRAM_COMPILER)-ccompiler)),$(SCRAM_COMPILER)-ccompiler,$(SCRAM_DEFAULT_COMPILER)-ccompiler)
ccompiler_EX_USE    := $(ccompiler_LOC_USE)
ccompiler_INIT_FUNC := $$(eval $$(call ProductCommonVars,ccompiler,,,ccompiler))


f77compiler := f77compiler
ALL_TOOLS  += f77compiler
f77compiler_LOC_USE   := $(if $(strip $(wildcard $(LOCALTOP)/$(SCRAM_TOOLS_DIR)/$(SCRAM_COMPILER)-f77compiler)),$(SCRAM_COMPILER)-f77compiler,$(SCRAM_DEFAULT_COMPILER)-f77compiler)
f77compiler_EX_USE    := $(f77compiler_LOC_USE)
f77compiler_INIT_FUNC := $$(eval $$(call ProductCommonVars,f77compiler,,,f77compiler))

CMSSW_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/cms/cmssw/CMSSW_6_1_1
PROTOBUF_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/protobuf/2.4.1
BINDIR:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/protobuf/2.4.1/bin
LIBTIFF_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/libtiff/3.9.4
CLHEP_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/clhep/2.1.1.0-cms2
HERWIG_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/herwig/6.520
LAPACK_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/lapack/3.3.1-cms2
LIBHEPML_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/libhepml/0.2.1
BOOST_PYTHON_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/boost/1.51.0-cms2
PYSTE_EXEC:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/boost/1.51.0-cms2/lib/python2.7/site-packages/Pyste/pyste.py
GSL_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/gsl/1.10
PY2_CJSON_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/py2-cjson/1.0.5-cms4
QT3SUPPORT_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/qt/4.8.1
QTEXTRA_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/qt/4.8.1
ROOTRFLX_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/lcg/root/5.34.03-cms4
RIVET_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/rivet/1.8.1
QTDESIGNER_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/qt/4.8.1
DPM_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/dpm/1.8.0.1
XROOTD_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/xrootd/3.2.4-cms2
XDAQ_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/xdaq/VR17173-cms2
GEANT4DATA_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external
MAKE_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/gmake/3.81
ifeq ($(strip $(SCRAM_COMPILER)),distcc)
CXX:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/distcc/3.2rc1/bin/c++
endif
HEPMC_HEADERS_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/hepmc/2.06.07
DCAP_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/dcap/2.47.5.0
JIMMY_HEADERS_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/jimmy/4.2
FRONTIER_CLIENT_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/frontier_client/2.8.5-cms
EVTGENLHC_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/evtgenlhc/9.1-cms2
LLVM_CCOMPILER_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/llvm/3.2-cms2
ifeq ($(strip $(SCRAM_COMPILER)),llvm)
CC:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/llvm/3.2-cms2/bin/clang
endif
CASCADE_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/cascade/2.2.04
MCTESTER_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/mctester/1.25.0a-cms7
BOOSTHEADER_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/boost/1.51.0-cms2
PYTHIA6_HEADERS_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/pythia6/426
CASTOR_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/castor/2.1.13.6-cms
PY2_IPYTHON_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/py2-ipython/0.10-cms4
XDAQHEADER_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/xdaq/VR17173-cms2
TOPREX_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/toprex/4.23
PY2_MATPLOTLIB_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/py2-matplotlib/1.0.1-cms5
BOOST_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/boost/1.51.0-cms2
UUID_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/uuid/1.38-cms
SIP_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/sip/4.11.2-cms4
TCMALLOC_MINIMAL_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/google-perftools/1.6
ORACLE_ADMINDIR:=/afs/cern.ch/cms/slc5_amd64_gcc472/cms/oracle-env/29/etc
LCOV_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/lcov/1.9
DAS_CLIENT_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/cms/das-client/1.4.1-cms4
PYTHON_LDAP_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/python-ldap/2.3.5-cms4
PYTHON_LDAP_PYPATH:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/python-ldap/2.3.5-cms4/lib/python2.7/site-packages
ZLIB_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/zlib/1.2.3
PYMINUIT2_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/pyminuit2/0.0.1-cms9
XZ_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/xz/5.0.3-cms
LLVM_ANALYZER_CXXCOMPILER_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/llvm/3.2-cms2
ifeq ($(strip $(SCRAM_COMPILER)),llvm-analyzer)
CXX:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/llvm/3.2-cms2/bin/c++-analyzer
endif
LIBXML2_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/libxml2/2.7.7
XERCES_C_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/xerces-c/2.8.0-cms
LLVM_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/llvm/3.2-cms2
MCDB_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/mcdb/1.0.2-cms
DB4_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/db4/4.4.20
SHERPA_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/sherpa/1.4.2
PYTHIA6_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/pythia6/426
ifeq ($(strip $(SCRAM_COMPILER)),distcc)
CC:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/distcc/3.2rc1/bin/gcc
endif
GEANT4CORE_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/geant4/9.5.p02
G4LIB:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/geant4/9.5.p02/lib
ELEMENTTREE_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/elementtree/1.2.6-cms4
ELEMENTTREE_PYPATH:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/elementtree/1.2.6-cms4/share/lib/python2.7/site-packages
GCCXML_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/gccxml/20110825-cms2
FFTW3_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/fftw3/3.3.2
THEPEG_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/thepeg/1.7.0
LLVM_ANALYZER_CCOMPILER_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/llvm/3.2-cms2
ifeq ($(strip $(SCRAM_COMPILER)),llvm-analyzer)
CC:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/llvm/3.2-cms2/bin/ccc-analyzer
endif
SIGCPP_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/sigcpp/2.2.10
QT_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/qt/4.8.1
PYQT_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/pyqt/4.8.1-cms4
HEPMC_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/hepmc/2.06.07
PCRE_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/pcre/7.9
TAUOLA_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/tauola/27.121.5
LHAPDF_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/lhapdf/5.8.5
ifeq ($(strip $(SCRAM_COMPILER)),ccache)
CC:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/ccache/3.1.8/bin/gcc
endif
ifeq ($(strip $(SCRAM_COMPILER)),ccache)
CXX:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/ccache/3.1.8/bin/c++
export CCACHE_BASEDIR:=/afs/cern.ch/cms/slc5_amd64_gcc472/cms/cmssw/CMSSW_6_1_1
endif
ifeq ($(strip $(SCRAM_COMPILER)),llvm)
FC:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/gcc/4.7.2/bin/gfortran
endif
MILLEPEDE_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/millepede/03.04.01-cms3
ROOTCINT_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/lcg/root/5.34.03-cms4
OPENSSL_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/openssl/0.9.8e__1.0.1
CURL_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/curl/7.28.0
TBB_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/tbb/41_20120718oss
ifeq ($(strip $(SCRAM_COMPILER)),ccache)
FC:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/ccache/3.1.8/bin/gfortran
endif
PYDATA_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/pythia6/426
ALPGEN_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/alpgen/213
LIBUNGIF_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/libungif/4.1.4
PY2_CX_ORACLE_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/py2-cx-oracle/5.1-cms5
GRAPHVIZ_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/graphviz/2.16.1
CMSSWDATA_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/cms
CMSSW_DATA_PATH:=/afs/cern.ch/cms/slc5_amd64_gcc472/cms
PY2_NUMPY_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/py2-numpy/1.6.1-cms5
HECTOR_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/hector/1_3_4-cms9
JEMALLOC_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/jemalloc/2.2.2
QTBASE_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/qt/4.8.1
TAUOLA_HEADERS_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/tauola/27.121.5
PYTHON_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/python/2.7.3-cms4
PYTHON_COMPILE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/python/2.7.3-cms4/lib/python2.7/compileall.py
TKONLINESW_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/tkonlinesw/2.7.0-cms4
KTJET_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/ktjet/1.06-cms2
VDT_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/cms/vdt/v0.2.3
PYTHIA8_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/pythia8/165
BZ2LIB_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/bz2lib/1.0.5
GDB_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/gdb/7.5-cms2
LIBJPEG_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/libjpg/8b
ifeq ($(strip $(SCRAM_COMPILER)),distcc)
FC:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/distcc/3.2rc1/bin/gfortran
endif
CASCADE_HEADERS_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/cascade/2.2.04
GDBM_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/gdbm/1.10
DBS_CLIENT_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/cms/dbs-client/DBS_2_1_9-cms3
CPPUNIT_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/cppunit/1.12.1
FFTJET_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/fftjet/1.3.1-cms
EXPAT_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/expat/2.0.1
PY2_PYCURL_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/py2-pycurl/7.19.0-cms5
PROFESSOR_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/professor/1.0.0-cms9
HERWIGPP_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/herwigpp/2.5.0
ROOT_INTERFACE_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/lcg/root/5.34.03-cms4
CASTOR_HEADER_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/castor/2.1.13.6-cms
TAUOLAPP_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/tauolapp/1.0.5
MIMETIC_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/mimetic/0.9.6
HEPPDT_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/heppdt/3.03.00
CORAL_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/cms/coral/CORAL_2_3_21-cms10
PY2_LINT_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/py2-lint/0.25.1-cms4
OPENLDAP_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/openldap/2.3.39
LIBPNG_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/libpng/1.2.46
PHOTOS_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/photos/215.5
SQLITE_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/sqlite/3.7.10
CLHEPHEADER_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/clhep/2.1.1.0-cms2
JIMMY_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/jimmy/4.2
PY2SHIPY_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/py2-scipy/0.8.0-cms5
CLASSLIB_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/classlib/3.1.3-cms2
VALGRIND_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/valgrind/3.8.0
IGPROF_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/igprof/5.9.5-cms
TCMALLOC_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/google-perftools/1.6
ORACLE_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/oracle/11.2.0.3.0__10.2.0.4.0
LLVM_CXXCOMPILER_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/llvm/3.2-cms2
ifeq ($(strip $(SCRAM_COMPILER)),llvm)
CXX:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/llvm/3.2-cms2/bin/clang++
endif
MESCHACH_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/meschach/1.2.pCMS1
TOPREX_HEADERS_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/toprex/4.23
ROOFIT_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/lcg/roofit/5.34.04-cms2
GLIMPSE_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/glimpse/4.18.5
PHOTOS_HEADERS_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/photos/215.5
CHARYBDIS_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/charybdis/1.003
FASTJET_BASE:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/fastjet/3.0.1
############## All SCRAM ENV variables ################
LOCALTOP:=/afs/cern.ch/cms/slc5_amd64_gcc472/cms/cmssw/CMSSW_6_1_1
SCRAM_TMP:=tmp
SCRAM_INIT_LOCALTOP:=/afs/cern.ch/cms/slc5_amd64_gcc472/cms/cmssw/CMSSW_6_1_1
SCRAM_BUILDFILE:=BuildFile
SCRAM_INTlog:=logs
SCRAM_GMAKE_PATH:=/afs/cern.ch/cms/slc5_amd64_gcc472/external/gmake/3.81/bin/
SCRAM_INTwork:=tmp/slc5_amd64_gcc472
SCRAM_PROJECTNAME:=CMSSW
SCRAM_SOURCEDIR:=src
SCRAM_ARCH:=slc5_amd64_gcc472
SCRAM_RTBOURNE_SET:=CMSSW:CMSSW_6_1_1:slc5_amd64_gcc472:V2_2_4_pre9:SRT_
SCRAM_CONFIGCHKSUM:=3b148e9af501cb71139042b7b29169b0
SCRAM_LOOKUPDB_WRITE:=/afs/cern.ch/cms
SCRAM_PROJECTVERSION:=CMSSW_6_1_1
SCRAM_CONFIGDIR:=config
################ ALL SCRAM Stores #######################
ALL_PRODUCT_STORES:=
SCRAMSTORENAME_LOGS:=logs/slc5_amd64_gcc472
ALL_PRODUCT_STORES+=$(SCRAMSTORENAME_LOGS)
SCRAMSTORENAME_LIB:=lib/slc5_amd64_gcc472
ALL_PRODUCT_STORES+=$(SCRAMSTORENAME_LIB)
SCRAMSTORENAME_INCLUDE:=include
ALL_PRODUCT_STORES+=$(SCRAMSTORENAME_INCLUDE)
SCRAMSTORENAME_CFIPYTHON:=cfipython/slc5_amd64_gcc472
ALL_PRODUCT_STORES+=$(SCRAMSTORENAME_CFIPYTHON)
SCRAMSTORENAME_OBJS:=objs/slc5_amd64_gcc472
ALL_PRODUCT_STORES+=$(SCRAMSTORENAME_OBJS)
SCRAMSTORENAME_DOC:=doc
ALL_PRODUCT_STORES+=$(SCRAMSTORENAME_DOC)
SCRAMSTORENAME_TEST:=test/slc5_amd64_gcc472
ALL_PRODUCT_STORES+=$(SCRAMSTORENAME_TEST)
SCRAMSTORENAME_PYTHON:=python
ALL_PRODUCT_STORES+=$(SCRAMSTORENAME_PYTHON)
SCRAMSTORENAME_BIN:=bin/slc5_amd64_gcc472
ALL_PRODUCT_STORES+=$(SCRAMSTORENAME_BIN)
