python sobWeightedCombineAll.py --category "0jet" --channel "mt et em"
python sobWeightedCombineAll.py --category "1jet" --channel "mt et em tt"
python sobWeightedCombineAll.py --category "vbf" --channel "mt et em tt"
python sobWeightedCombineAll.py --channel "mt et em tt"
#python sobWeightedCombineAll.py --channel "mt et" --category 'vbf' --mode "Mtt"